service: face-align-exp

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-south-1
  timeout: 60
  environment:
    S3_BUCKET: draj-models
    MODEL_PATH: shape_predictor_5_face_landmarks.dat
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:getObject
      Resource: arn:aws:s3:::draj-models/*

custom:
  pythonRequirements:
    dockerizePip: true
    zip: true
    strip: false
    useStaticCache: true
    useDownloadCache: true
    cacheLocation: "./cache"

package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**
    - cache/**
    - test/**
    - __pycache__/**
    - .pytest_cache/**
    - model/**

functions:
  classify_image:
    handler: handler.classify_image
    memorySize: 3008
    timeout: 60
    events:
      - http:
          path: classify
          method: post
          cors: true

plugins:
  - serverless-python-requirements
