name: GitHub Classroom Workflow

on:
    push:
        paths:
          - eva/python/qualean/*
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: education/autograding@v1
